name: NPM Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - run: yarn install
      - run: yarn build
